language: node_js
branches:
  only:
  - master
node_js:
- 10.13.0
env:
- NODE_ENV=PRODUCTION
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- cd frontend-payment
- rm -rf node_modules
- yarn --frozen-lockfile
- yarn build
- cd ..
- rm -rf server-payment/frontend-dist/
- cp -R frontend-payment/build/ server-payment/frontend-dist/
- cd server-payment
- rm -rf node_modules
- yarn --frozen-lockfile
- yarn build
- cd ..
script:
- echo "There are no tests"
cache:
  directories:
  - "$HOME/.cache/yarn"
  - "$HOME/.npm"
before_deploy:
- cd server-payment
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: aKRO2XuAPq+8d+C0eEtbKiRiTB3uBrbHTehEd/CJ/ii7nDKyls6sHulM8TgVMMS/MIaM2TZICubbEKpOeIX4svturAhzRGm++aoOy0JoBQLcLAlG6uQSMswF3wz5Q6xdlrjMYrvyYcFj1jKlKS376e4rW+2jJXPAqebODNpo3mq7fbs/V/hDBG4A95PCrMz+NtXbTqiplKVkzxpPmtS+GbGZbeVXUk3upou+2B+2yb2Vk57inJo/HniDxN8bnQU36NR0IPwL5HuOe1TqjnIurI37tjE+ZdjH8C7M2WthtrZ4hR8Sd33nFp2JyP5loRbpHKN7UMHelWSrsHwVR4mhYcd4P6OKxasAKGmcIN002vcySUMR4CrQyoc2n1WHn4bnpMrV0LHEFXPAEa7Bjk/huEUD8is4OG7gJzjD66H+iN/cGpxTTSM99gLcYfBHJSnyhbvnkaTgtVZBzWkkJOAEXrUvqANpTg+rwzgJhiKP4190irfDU2zm3NQUIt5Xi7Ir+Pv50Azs3tBYT9xFIYoW0ZT/O36IRL5VB724V341/IhjLtu96zwjbdrrpwcHsNpEWUDGy9CUZEMVxLkPt/VO8p2UeDAraO+4HpQ6dYzICkRjiwWefvZQOwa9eptcKnb4kpMFyee3ley5lg47GPAIzeyiZtTQsVlE5ZdR4ZpLYyA=
  app: payda-support-v2
  on:
    repo: paydaplatformu/payda-support
