version: "3.7"
services:
  mongodb:
    image: mongo:3.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=payda
      - MONGO_INITDB_ROOT_PASSWORD=paydapw
      - MONGO_INITDB_DATABASE=paydadb
    volumes:
      - docker-data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
volumes:
  docker-data: